### ISSUE TITLE
Error downloading ftp.vital-it.ch/papers/vital-it/Bioinformatics-Schaper/substitution_rate_matrices/lg.dat

### ISSUE THREAD

**Issue by tyrarsin** [elkeschaper/tral#50]
Unfortunately when calculating the p-value, as [described in the tutorial](https://acg-team.github.io/tral/significance_test.html#significance-test), TRAL fails. 

It tries to download a file from vital-it.ch, but unfortunately the desired file isn't present anymore.
"FileNotFoundError: Error downloading ftp://ftp.vital-it.ch/papers/vital-it/Bioinformatics-Schaper/substitution_rate_matrices/lg.dat"

Did I miss something or got the file deleted?

Many thanks in advance!

> Traceback (most recent call last):
  File "tandem_test.py", line 12, in <module>
    iTandemRepeat.calculate_pvalues()
  File "/home/tyrarsin/anaconda3/envs/masterarbeit/lib/python3.8/site-packages/tral-2.0.1.dev0-py3.8.egg/tral/repeat/repeat.py", line 386, in calculate_pvalues
    repeat_pvalue.pvalue_from_empirical_list(self, 'phylo_gap01')
  File "/home/tyrarsin/anaconda3/envs/masterarbeit/lib/python3.8/site-packages/tral-2.0.1.dev0-py3.8.egg/tral/repeat/repeat_pvalue.py", line 125, in pvalue_from_empirical_list
    score_value = tandemrepeat.score(score_type)
  File "/home/tyrarsin/anaconda3/envs/masterarbeit/lib/python3.8/site-packages/tral-2.0.1.dev0-py3.8.egg/tral/repeat/repeat.py", line 151, in score
    self.calculate_scores(scoreslist=[score_type])
  File "/home/tyrarsin/anaconda3/envs/masterarbeit/lib/python3.8/site-packages/tral-2.0.1.dev0-py3.8.egg/tral/repeat/repeat.py", line 316, in calculate_scores
    repeat_score.phylo_star_topology_local(self,
  File "/home/tyrarsin/anaconda3/envs/masterarbeit/lib/python3.8/site-packages/tral-2.0.1.dev0-py3.8.egg/tral/repeat/repeat_score.py", line 592, in phylo_star_topology_local
    logLH0 = loglikelihood_random(
  File "/home/tyrarsin/anaconda3/envs/masterarbeit/lib/python3.8/site-packages/tral-2.0.1.dev0-py3.8.egg/tral/repeat/repeat_score.py", line 557, in loglikelihood_random
    aarate_file_name = config_file(
  File "/home/tyrarsin/anaconda3/envs/masterarbeit/lib/python3.8/site-packages/tral-2.0.1.dev0-py3.8.egg/tral/paths.py", line 86, in config_file
    raise FileNotFoundError("Error downloading %s" % url)
FileNotFoundError: Error downloading ftp://ftp.vital-it.ch/papers/vital-it/Bioinformatics-Schaper/substitution_rate_matrices/lg.dat

**Comment by sbliven** [comment]
The error message is a little misleading. TRAL is actually expecting `~/.tral/data/ALF/lg.dat` to exist. If it doesn't then it tries to download it (but it's not in the pvalue bundle so that fails).

The file should be included with your tral installation. Can you describe how you installed tral (pip, the tral easy_install scripts, etc) and what version you're using?

If you have tral 2.0 you can probably work around this issue by reinstalling the data:

    python -m tral install

This should create `~/.tral/data/ALF/lg.dat` .

**Comment by matteodelucchi** [comment]
I assume this is solved.
