### ISSUE TITLE
Tools do not work within the docker container

### ISSUE THREAD

**Issue by JoanaMPereira** [elkeschaper/tral#54]
Hello,

We have been trying to setup TRAL and have been running into some issues using the container. We are able to use TRAL as a python module but when predicting repeats with any of the tools, they either do not give any result or crash with an error message. We tested with a protein sequence that has repeat units, detectable when running HHrepID using the MPI bioinformatics tool (UniProt AC A0A010PZU8), testing each individual detector using the command `tandem_repeats = sequence.detect(denovo = True, detection = {"detectors": [<detector>]})`. 

This is the output for each try:

```
XSTREAM
Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/sequence.py", line 178, in detect **kwargs['detection'])[0] File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 976, in run_detector Detectors(detectors, sequence_type) File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 888, in Detectors DETECTORS = {FINDER_LIST[i].name: FINDER_LISTi for i in lDetector} File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 888, in <dictcomp> DETECTORS = {FINDER_LIST[i].name: FINDER_LISTi for i in lDetector} File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 802, in init name=name) File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 62, in init binary, name)) ValueError: The executable XSTREAM does not exist, although XSTREAM was selected to be executed. Please make sure the executable is in the system path, or the path to the executable is set correctly in config.ini
```
```
HHrepID
Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/sequence.py", line 178, in detect **kwargs['detection'])[0] File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 976, in run_detector Detectors(detectors, sequence_type) File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 888, in Detectors DETECTORS = {FINDER_LIST[i].name: FINDER_LISTi for i in lDetector} File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 888, in <dictcomp> DETECTORS = {FINDER_LIST[i].name: FINDER_LISTi for i in lDetector} File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 256, in init self.config = self.Configuration() File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 210, in init raise FileNotFoundError("HHrepID_dummyhmm not found: %s" % dummyhmm) FileNotFoundError: HHrepID_dummyhmm not found: /root/.tral/data/hhrepid/dummyHMM.hmm
```
```
T-REKS
No reaction
```
```
TRED
Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/sequence.py", line 178, in detect **kwargs['detection'])[0] File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 976, in run_detector Detectors(detectors, sequence_type) File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 888, in Detectors DETECTORS = {FINDER_LIST[i].name: FINDER_LISTi for i in lDetector} File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 888, in <dictcomp> DETECTORS = {FINDER_LIST[i].name: FINDER_LISTi for i in lDetector} File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 444, in init name=name) File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 62, in init binary, name)) ValueError: The executable tred does not exist, although TRED was selected to be executed. Please make sure the executable is in the system path, or the path to the executable is set correctly in config.ini
```
```
Phobos 
no reaction
```
```
TRF
no reaction
```
```
TRUST
Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/sequence.py", line 178, in detect **kwargs['detection'])[0] File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 976, in run_detector Detectors(detectors, sequence_type) File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 888, in Detectors DETECTORS = {FINDER_LIST[i].name: FINDER_LISTi for i in lDetector} File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 888, in <dictcomp> DETECTORS = {FINDER_LIST[i].name: FINDER_LISTi for i in lDetector} File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 706, in init name=name) File "/usr/local/lib/python3.6/dist-packages/tral-2.0-py3.6.egg/tral/sequence/repeat_detection_run.py", line 62, in init binary, name)) ValueError: The executable TRUST does not exist, although TRUST was selected to be executed. Please make sure the executable is in the system path, or the path to the executable is set correctly in config.ini
```

Can you suggest what is the best way to proceed?

Many thanks!
Joana

**Comment by matteodelucchi** [comment]
1. Could you elaborate a bit more on the issues you were experiencing with docker?
2. Local installation of TRAL works best with [`easy_setup`](https://github.com/acg-team/tral/tree/develop/easy_setup). It is possible, however, that the servers to download the installation files for the external tools are not responding (one of the reasons to go for docker). Also, correctly setting up all environmental variables can be quite tricky (another reason for docker or `easy_setup`).
a. Could you verify that your installation of TRAL is correctly configured? 
b. Could you provide a MRE?
